### ISSUE TITLE
Improving Quality Settings for Generation Output

### ISSUE THREAD

**Issue by yachty66** [Tencent/MimicMotion#14]
What settings can I change if I want to adjust the quality of the generation? For example, if I would like to enhance the output quality, what steps can I take or settings can I adjust?

**Comment by G-force78** [comment]
FPS, inference steps

**Comment by zyayoung** [comment]
You may adjust guidance_scale for higher quality. For the demos, we use guidance_scale=3

**Comment by yachty66** [comment]
Adjusting parameters inside of https://github.com/Tencent/MimicMotion/blob/main/configs/test.yaml helped me in closing the issue.

**Comment by longcw** [comment]
> You may adjust guidance_scale for higher quality. For the demos, we use guidance_scale=3

Thank you for this great work! Could you explain why a higher `guidance_scale` works better, and why it's not the default setting?

**Comment by adit-0503** [comment]
@zyayoung could you explain the other parameters such as `fps`, `num_frames`, `frames_overlap`, `noise_aug_strength`, `sample_stride` - that would be very helpful

**Comment by nitinmukesh** [comment]
@yachty66 

Please could you help with what settings you changed to achieve good results.
