### ISSUE TITLE
OSError: Error no file named config.json found in directory models/SVD/stable-video-diffusion-img2vid-xt-1-1.

### ISSUE THREAD

**Issue by DannyWu25** [Tencent/MimicMotion#16]
![微信截图_20240703231944](https://github.com/Tencent/MimicMotion/assets/96119579/c2c1ad32-fabb-4864-9e7b-b3cc2799b6b8)
![微信截图_20240703231955](https://github.com/Tencent/MimicMotion/assets/96119579/c5fb3a2f-e89b-4e6c-9737-bb8ff1229bc1)
Please, can someone tell me where is the config.json file ？

**Comment by soltkreig** [comment]
Check you folder, usually it happens because one of folder has not been cloned - unet, vae, scheduler of image_encoder

**Comment by DannyWu25** [comment]
> Check you folder, usually it happens because one of folders has not been cloned - unet, vae, scheduler of image_encoder

I downloaded it one by one because cloning directly would result in an error message

**Comment by DannyWu25** [comment]
> pls show you dir structure

![微信截图_20240704182308](https://github.com/Tencent/MimicMotion/assets/96119579/e53e723a-60cc-4ab9-96a6-98bf72a4409f)
Is there anything missing

**Comment by soltkreig** [comment]
show structure of image_encode, scheduler, unet and vae folders pls

**Comment by DannyWu25** [comment]
> 请显示 image_encode、scheduler、unet 和 vae 文件夹的结构

![微信截图_20240704183340](https://github.com/Tencent/MimicMotion/assets/96119579/a6ba0f27-8d85-40c2-be72-5533998d547f)
![微信截图_20240704183351](https://github.com/Tencent/MimicMotion/assets/96119579/f771d0a1-b874-4578-b1c7-04523abcbbb3)
![微信截图_20240704183407](https://github.com/Tencent/MimicMotion/assets/96119579/10210e3d-a8b1-417b-bf10-dad1b93454cf)
![微信截图_20240704183420](https://github.com/Tencent/MimicMotion/assets/96119579/a47c73f0-49e6-46c0-8769-f15af40a467d)
![微信截图_20240704183439](https://github.com/Tencent/MimicMotion/assets/96119579/0cca9e1d-1c0c-4265-b970-4e37c546b39e)
This is all I have

**Comment by soltkreig** [comment]
rename you configs as on screenshot:
![image](https://github.com/Tencent/MimicMotion/assets/69303309/1cc7cd4f-3628-47e9-bba3-e64354b80e0b)

**Comment by DannyWu25** [comment]
> 按照屏幕截图重命名您的配置，由于配置名称错误，您无法运行 repo： ![图像](https://private-user-images.githubusercontent.com/69303309/345801429-1cc7cd4f-3628-47e9-bba3-e64354b80e0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTAxMDMsIm5iZiI6MTcyMDA4OTgwMywicGF0aCI6Ii82OTMwMzMwOS8zNDU4MDE0MjktMWNjN2NkNGYtMzYyOC00N2U5LWJiYTMtZTY0MzU0YjgwZTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDEwNDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZDIxOTE1NDQ2ZWY1ZmE0YTNkMDY2ODgwMThmMjY2ZGVkYTUxMjBkNzhkOTJjMDM5ZTc3ZTU5YzIwYWY2OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GmALAjUeV7lIrr_v3m8BF4EnCNxQZfLFraO7AeQAktA)

![微信截图_20240704185304](https://github.com/Tencent/MimicMotion/assets/96119579/c6d31922-4959-4586-9f1c-21450cc955dd)
It looks like it's working

**Comment by DannyWu25** [comment]
> @DannyWu25 See if the installation steps help https://www.youtube.com/watch?v=PYIFvzV1KoE

thanks，let me take a look

**Comment by DannyWu25** [comment]
> rename you configs as on screenshot, you cannot run repo because of wrong config names: ![image](https://private-user-images.githubusercontent.com/69303309/345801429-1cc7cd4f-3628-47e9-bba3-e64354b80e0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNDUwMTAsIm5iZiI6MTcyMDE0NDcxMCwicGF0aCI6Ii82OTMwMzMwOS8zNDU4MDE0MjktMWNjN2NkNGYtMzYyOC00N2U5LWJiYTMtZTY0MzU0YjgwZTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAxNTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkOWI4YjI4ZWM5ZDQ4ZmIzOTNlNGJmNTVmMjFiNWQzODBhYzJmYTQ1MWQ4M2IxM2QwMzVjNWY0YWNjMTUxODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vP2_lPtFgg4zC1wPXubnafPNNuNAil52X0y-3Ru2MxU)

thanks a lot
