### ISSUE TITLE
学习Animate快加学习交流群

### ISSUE THREAD

**Issue by km1994** [Tencent/MimicMotion#19]
最近在学习的Animate 的可以加群讨论

![a2e66f40aac7800fb6d3c7be4373159](https://github.com/Tencent/MimicMotion/assets/7261924/fadfea1f-1bfc-4f5a-80e0-bf67b7243e6f)

**Comment by dunknsabsw** [comment]
人数超过200了 加不进去

**Comment by km1994** [comment]
加wx: yzyykm666，备注：Animate ，邀请你加群哈！！！
