### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by RecordK** [Tencent/MimicMotion#25]
MimicMotion/inference.py", line 89, in main
    pipeline = create_pipeline(infer_config, device)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/MimicMotion/mimicmotion/utils/loader.py", line 43, in create_pipeline
    mimicmotion_models.load_state_dict(torch.load(infer_config.ckpt_path, map_location=device), strict=False)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

anaconda3/envs/mm/lib/python3.11/site-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

anaconda3/envs/mm/lib/python3.11/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)

**Comment by MoroseYu** [comment]
Hello, how is this problem solved?
