### ISSUE TITLE
About training the 72 frames models.

### ISSUE THREAD

**Issue by jiangzhengkai** [Tencent/MimicMotion#28]
Hi, in my case, the GPU memory usage already reaches 66GB with 16 frames at 1024 x 576 resolution and all convolutional parts checkpointed. What tricks do you use for training with 72 frames?

More checkpointing on  TransformerTemporalModel and TransformerSpatioTemporalModel really helps a lot.

**Comment by YuzhiChen001** [comment]
Hi, where did you find the training code?

**Comment by jiangzhengkai** [comment]
@YuzhiChen001 I implement it in my own training code, you can refer to [svd_xtend](https://github.com/pixeli99/SVD_Xtend)

**Comment by bruinxiong** [comment]
@jiangzhengkai Could you give more detailed information about training data ? Is there any download link ?

**Comment by jiangzhengkai** [comment]
@jiangzhengkai You need to collect videos by yourself whether from video platforms. As I know, there is no much public high-quality dancing videos.
