### ISSUE TITLE
用动漫人物生成很丑

### ISSUE THREAD

**Issue by CanvaChen** [Tencent/MimicMotion#37]
参考图：
![00027](https://github.com/Tencent/MimicMotion/assets/18375123/ffc2f9fd-fb8c-4876-9e23-2db81fac7573)

结果图：
![image](https://github.com/Tencent/MimicMotion/assets/18375123/de36b35e-7442-4aa3-9d2c-34ac2f42feaa)

**Comment by Bowen-Jian** [comment]
确实丑...
