### ISSUE TITLE
ModuleNotFoundErrors 

### ISSUE THREAD

**Issue by TheGermanEngie** [Tencent/MimicMotion#39]
Hi - 

I really have high hopes in using your project for some creative things but I keep running into a problem that is so simple it shouldn't even be happening, but somehow it is. I follow the instructions word for word, and activate the environment. Downloaded all the models in the right folders. However, when I try and run the default script (python inference.py --inference_config configs/test.yaml), I get this first error:

`Traceback (most recent call last):
  File "C:\Users\Ben\Documents\MimicMotion\inference.py", line 24, in <module>
    from mimicmotion.dwpose.preprocess import get_video_pose, get_image_pose
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\preprocess.py", line 5, in <module>
    from .util import draw_pose
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\util.py", line 3, in <module>
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'`

Then when I go and install matplotlib through conda (conda install matplotlib), running it again gives me another module error:

`Traceback (most recent call last):
  File "C:\Users\Ben\Documents\MimicMotion\inference.py", line 24, in <module>
    from mimicmotion.dwpose.preprocess import get_video_pose, get_image_pose
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\preprocess.py", line 5, in <module>
    from .util import draw_pose
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\util.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'`

It is acting like I created this in a base conda environment, which I didn't, I ran and activated the environment.yaml, so I'm not sure what's going on. If you have any ideas or suggestions that would be very appreciated, I tried this on Windows and Linux and get the same result.

**Comment by instructcode** [comment]
I got through all the errors by manualling pip installing those.

pip install matplotlib
pip install opencv-python
pip install opencv-contrib-python
huggingface-cli login
pip install PyAV

I am currently stumped at there error: av.codec.codec.UnknownCodecError: libx264
It seems to fail at the end.

**Comment by theoldsong** [comment]
> I am currently stumped at this error: av.codec.codec.UnknownCodecError: libx264 It seems to fail at the end.

I have also encountered the same problem as you

**Comment by theoldsong** [comment]
> I got through all the errors by manualling pip installing those.
> 
> pip install matplotlib pip install opencv-python pip install opencv-contrib-python huggingface-cli login pip install PyAV
> 
> I am currently stumped at this error: av.codec.codec.UnknownCodecError: libx264 It seems to fail at the end.

I have found a solution

conda uninstall ffmpeg
conda install -c conda-forge ffmpeg

**Comment by Youne-Yu** [comment]
In my conda envs: torch220_cu118_py310
pip install diffusers transformers==4.32.1 decord==0.6.0 einops omegaconf tqdm matplotlib opencv_python onnxruntime-gpu accelerate av
ps: diffusers 0.27~0.29.2 is OK

**Comment by TheGermanEngie** [comment]
> In my conda envs: torch220_cu118_py310 pip install diffusers transformers==4.32.1 decord==0.6.0 einops omegaconf tqdm matplotlib opencv_python onnxruntime-gpu accelerate av ps: diffusers 0.27~0.29.2 is OK

I tried making a new environment as such:

name: mimicmotion1
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - diffusers==0.27.0
    - transformers==4.32.1
    - decord==0.6.0
    - einops
    - omegaconf
    - tqdm
    - matplotlib
    - opencv_python 
    - onnxruntime-gpu
    - accelerate
    - av

If "torch220_cu118_py310" means pytorch=2.2.0, python=3.10, and cu118=pytorch-cuda 11.8. I get this error

(mimicmotion1) PS C:\Users\Ben\Documents\MimicMotion> python inference.py --inference_config configs/test.yaml
C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: '[WinError 127] The specified procedure could not be found'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\transformers\utils\generic.py:260: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\Users\Ben\Documents\MimicMotion\inference.py", line 24, in <module>
    from mimicmotion.dwpose.preprocess import get_video_pose, get_image_pose
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\preprocess.py", line 6, in <module>
    from .dwpose_detector import dwpose_detector as dwprocessor
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\dwpose_detector.py", line 6, in <module>
    from .wholebody import Wholebody
  File "C:\Users\Ben\Documents\MimicMotion\mimicmotion\dwpose\wholebody.py", line 2, in <module>
    import onnxruntime as ort
  File "C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
  File "C:\Users\Ben\miniconda3\envs\mimicmotion1\lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
ImportError: DLL load failed while importing onnxruntime_pybind11_state: A dynamic link library (DLL) initialization routine failed.

**Comment by TheGermanEngie** [comment]
Update: have installed onnxruntime CPU version `pip uninstall onnxruntime-gpu`, `pip install onnxruntime,` which worked. And then it wouldn't clone the stable diffusion video model automatically without auth so I downloaded each one manually. 

It seems to be running so far, DWPose ran first (took 4 min on CPU), now looks like the main process is running and is taking around ~37 minutes on a 3090. Using CUDA and everything correctly. Will update in the future

**Comment by TheGermanEngie** [comment]
Confirmed, the following environment works:

do `conda uninstall ffmpeg`, then `conda install -c conda-forge ffmpeg`

name: mimicmotion_test
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - diffusers==0.27.0
    - transformers==4.32.1
    - decord==0.6.0
    - einops
    - omegaconf
    - tqdm
    - matplotlib
    - opencv_python 
    - onnxruntime-gpu
    - accelerate
    - av

Main changes are python 3.11 -> 3.10, pytorch 2.0.1 -> 2.2.0, pytorch-cuda 11.8. The rest are pip errors @Youne-Yu installed with pip earlier. Closing unless a new update or something breaks it and a new thread is started.
