### ISSUE TITLE
classification-free inference 和 normal inference 为什么不能组batch推理

### ISSUE THREAD

**Issue by akk-123** [Tencent/MimicMotion#62]
[代码中](https://github.com/Tencent/MimicMotion/blob/main/mimicmotion/pipelines/pipeline_mimicmotion.py#L568-L595) classification-free inference 和 normal inference 为什么要分开推理，不能组batch推理，提高推理速度吗

**Comment by zyayoung** [comment]
可以组batch的，分开是为了降低峰值显存占用，适配16G 4060ti
ref: https://github.com/Tencent/MimicMotion/pull/32#issue-2397978086
