### ISSUE TITLE
stable-video-diffusion-img2vid-xt-1-1无法下载

### ISSUE THREAD

**Issue by lidongliang666** [Tencent/MimicMotion#64]

**Comment by lidongliang666** [comment]
OSError: stabilityai/stable-video-diffusion-img2vid-xt-1-1 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `token` or log in with `huggingface-cli login`.

**Comment by yashtomar31** [comment]
Were you able to solve this ?

**Comment by lidongliang666** [comment]
> Were you able to solve this ?

yes,
首先在环境中安装pip install huggingface_hub，
使用 huggingface-cli login命令，设置Tokens。
然后再启动程序后，就会成功的自动下载模型了。

**Comment by gujiaxi** [comment]
@lidongliang666 @yashtomar31 You can try to manually download the model files from Huggingface and refer to file *configs/test.yaml* in this commit [#08f5e7c](https://github.com/Tencent/MimicMotion/commit/08f5e7c6315577ffe91b52eecb776b519927d4ed).

**Comment by yashtomar31** [comment]
Thanks everyone, it works after downloading it manually.

**Comment by dannyLq** [comment]
> > Were you able to solve this ?
> 
> yes, 首先在环境中安装pip install huggingface_hub， 使用 huggingface-cli login命令，设置Tokens。 然后再启动程序后，就会成功的自动下载模型了。

你好，请问怎样使用 huggingface-cli login命令，设置Tokens

**Comment by Anas-jaffery-kodexolab** [comment]
> Thanks everyone, it works after downloading it manually.

could you please tell what file you downloaded and where you put that file?

**Comment by mrtpk** [comment]
For those who still face this error:

1. Go to https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1
2. Request for access and once you have filled the data you will see the following

![image](https://github.com/user-attachments/assets/0950f3e8-7f61-4c9c-80d4-e80ae34f63d9)

3. Install huggingface cli `pip3 install -U "huggingface_hub[cli]"`
4. Run `python3 -c "from huggingface_hub.hf_api import HfFolder; HfFolder.save_token('Your HF token')"`
