### ISSUE TITLE
Extended Inference Time

### ISSUE THREAD

**Issue by yachty66** [Tencent/MimicMotion#7]
I am having a problem where, when I run the model for inference, it shows me that the inference time is about 40 minutes. I am following all the mentioned steps, with the only difference being the GPU (A40) instead of V100.

**Comment by vrgamegirl19** [comment]
Hey, how did u get it working? I literally spent 5 hours and still couldn't get it to work.  I'm thinking I'm missing files or my structure is wrong.  Can u take a screen grab  of your folders structure? I posted my issue in the issue list.

**Comment by xuanlongORZ** [comment]
I also come across this issue. I figure out that the the number of frames is too big for the given example. I put sample_stride in test.ymal as 8 and it's now able to generate a short video in around 15min using Nvidia L20 (it is better to set a lower fps for this moment).

**Comment by sweetgrass** [comment]
> I also come across this issue. I figure out that the the number of frames is too big for the given example. I put sample_stride in test.ymal as 8 and it's now able to generate a short video in around 15min using Nvidia L20 (it is better to set a lower fps for this moment).

老哥，这个跟之前的那个Muse Pose比，效果怎么样？

**Comment by yachty66** [comment]
It seems to be a normal inference time. With A100, it currently takes me 20 minutes to run the demo on inference. Closing this issue.
